[Global]
TrackerURL=https://ipm.corel.com/omni-tracking
TrackerURLInternal=https://dev.ipm.corel.public.corel.net/omni-tracking
track_all=disable
track_features=disable
track_ipm_features=disable
track_pirate_features=disable
track_internal=disable

; WinZip 25
[WinZip25]
buildnumbers=25.0.14245.0|25.0.14273.0
track_all=enable
track_features=enable
track_ipm_features=disable
track_pirate_features=disable
track_internal=disable
disable_features=SocialMedi

; WinZip 26
[WinZip26]
buildnumbers=26.0.14610.0|26.0.14611.0|26.0.14660.0
track_all=enable
track_features=enable
track_ipm_features=disable
track_pirate_features=disable
track_internal=disable


; Roxio Creator NXT5 (IPP ID)
[0563300128]
buildnumbers=18.0.40
track_all=enable
track_features=enable
track_ipm_features=disable
track_pirate_features=disable
track_internal=disable



; Roxio Creator NXT7 (IPP ID)
[0563300155]
buildnumbers=20.0|21.0.45|21.0.63|21.0.69|20.0.54
track_all=enable
track_features=enable
track_ipm_features=disable
track_pirate_features=disable
track_internal=disable

; Roxio Creator NXT8 (IPP ID)
[0563300192]
buildnumbers=21.0|21.1.5.9
track_all=enable
track_features=enable
track_ipm_features=disable
track_pirate_features=disable
track_internal=disable


; Roxio Creator NXT9 (IPP ID)
[0563300207]
buildnumbers=22.0|22.0.149.0|22.0.164.0
track_all=enable
track_features=enable
track_ipm_features=disable
track_pirate_features=disable
track_internal=disable
